// adventofcode.Day1.Solution.Solve();
// adventofcode.Day2.Solution.Solve();
// adventofcode.Day3.Solution.Solve();
// adventofcode.Day4.Solution.Solve();
// adventofcode.Day5.Solution.Solve();
// adventofcode.Day6.Solution.Solve();
// adventofcode.Day7.Solution.Solve();
// adventofcode.Day8.Solution.Solve();
// adventofcode.Day9.Solution.Solve();
// adventofcode.Day10.Solution.Solve();
// adventofcode.Day11.Solution.Solve();
// adventofcode.Day12.Solution.Solve();
adventofcode.Day13.Solution.Solve();
